import { Inter } from "next/font/google";
import "./globals.css";
import ContexProvider from "@/provider/contexProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Khabar Kinbo",
  description: "Generated by developer",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContexProvider>
        <div className="">
        {children}
        </div>
        </ContexProvider>
        </body>
    </html>
  );
}
